/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 16.12.2025 04:18:24

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10272;
#else
constexpr int kTensorArenaSize = 9248;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,4018 } };
const TfArray<1, float> quant0_scale = { 1, { 0.003890931373462081, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 98, 41, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 98, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 49, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 49, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -1593, 1309, 48, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 3.5249162465333939e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -7, -20, 30, -20, -19, 7, 30, -46, -9, 27, 32, 4, 16, -42, -2, -9, -12, -43, 11, -6, -39, 32, 37, 1, -25, -14, 24, -14, -8, -30, 9, -46, -1, 5, -29, -14, 3, -35, -53, 28, -20, -34, 32, 2, 21, -9, -2, -44, 13, -8, -40, -37, -5, -4, 8, 0, 14, -20, 73, -19, -16, -15, -15, -4, 12, 6, -24, 15, -19, 12, 3, -47, -27, 23, -13, 30, -3, -14, -6, -9, -25, -44, 26, -2, 33, -7, 23, -11, -38, 52, -28, -13, -11, 3, 8, -47, -54, -19, -8, 14, 9, 53, 18, 26, 28, -11, 39, 18, 20, 21, -4, 0, 2, -8, -16, -27, -9, 22, -16, 2, 59, 3, 43, 3, 7, -13, 13, -72, -10, -45, -43, 35, 66, -10, 44, 2, 19, -3, 39, 13, 3, -2, 0, -77, -26, -16, -49, 17, 3, -11, 44, -28, 0, 0, 26, 24, 65, -49, 8, -65, 6, -71, -102, 43, 20, 41, 42, 0, 34, 20, 49, 17, 39, -18, 20, -76, -23, -27, -21, 26, 68, -7, 18, 13, 20, 49, 23, 5, 16, -19, 23, -114, -4, 6, -75, 24, 36, 14, 45, 55, 25, 48, 65, 18, 56, -13, 50, -74, -41, -74, -86, -9, 28, -29, -28, 1, 72, 48, 4, 13, 41, -20, 7, -116, -84, -31, -70, -13, 41, -6, 13, -7, 51, 19, 19, -1, 6, 7, -6, -119, -49, -1, -101, -26, 47, -7, 20, 20, 33, 29, 26, 62, 66, 31, 24, -108, -23, -54, -40, 41, -5, -6, 25, 22, 0, 73, 46, 43, 65, -3, 3, -89, -43, -55, -47, -47, -7, -28, 40, -58, -13, -7, -1, -9, 30, 10, -56, -66, -33, 1, -10, -42, -24, -47, -22, 35, -5, -26, -11, -17, 4, 10, 37, -21, -31, -42, -1, -16, -31, 2, 9, 31, -7, 48, -24, -41, 13, 9, 0, -38, 13, -39, -34, -7, 23, 9, -26, 26, -1, -12, 31, -32, 53, 12, 9, -36, -42, -1, -28, 0, -37, -24, 3, 13, 31, -8, -18, 45, 44, -2, -4, -36, -11, -48, -42, -51, 48, -24, 2, 9, -7, -1, -6, -22, -13, -38, -26, 34, -35, -14, -12, 19, 63, 49, 31, 13, 5, 28, 12, 63, -24, 5, -6, -25, -51, 5, -34, 13, -30, -21, -16, -19, 17, 42, 40, -14, 51, 3, -30, -29, 
  18, 30, 11, -22, -15, 18, 22, -17, 14, 5, -9, 22, 27, 47, 5, 23, 21, 37, -15, 30, 19, 4, 0, -1, 13, 7, 34, 41, -2, -28, 35, -20, 26, 18, -7, -32, 49, -37, -21, 11, 19, -7, -18, -5, -17, -30, -17, 31, 16, 7, -5, -1, 13, 8, -2, 10, -3, 3, -16, 10, 29, 47, -22, 3, 41, 57, 26, 28, 35, -2, 26, 20, 5, 20, -18, 38, 4, 39, -22, -29, -11, 13, 15, 1, 27, 11, 2, 36, 48, -12, -33, 21, -10, 41, -15, 39, 2, -2, 34, 39, -30, -27, -52, -1, -17, -31, -83, -21, -10, 10, -10, 43, -42, -1, 51, 39, 3, 24, 22, 27, -9, 19, -67, -57, -4, 17, -7, -5, -16, 31, -12, 7, -30, -17, -29, -21, -33, -31, -83, 0, 14, -37, 37, 1, -23, 21, 58, 1, -38, -1, -27, 1, -11, -9, -50, -18, -46, 8, -4, 48, 24, 67, 17, 16, -19, -42, -29, -20, -51, -19, -114, -8, 4, -23, 6, 30, 41, 13, 56, 22, -46, -12, -32, -17, -48, -36, -81, -86, -104, 35, -48, 127, 29, 3, 46, -30, 27, -66, -83, 24, -62, -84, -112, -58, -91, 16, 3, 72, 57, -2, 8, 25, -3, -60, -96, -12, -65, -9, -115, -75, -75, 39, -12, 108, 3, 65, 58, 34, 16, -51, -17, -14, -3, -33, -75, -50, -28, -18, 17, 57, 17, 32, 58, 46, -16, -54, -25, 23, -76, -76, -71, -29, -28, 13, -26, 40, 33, -7, 2, -15, -38, -64, -55, 40, -14, -22, -111, -29, -69, -21, 22, 70, 14, 49, 15, 9, 18, -56, -65, -36, -11, 0, -55, -55, -54, 26, -22, 7, 21, 10, 45, -28, -16, -41, -45, 8, -22, -54, -34, -63, -41, -23, -5, 53, 12, 46, -31, -31, 28, -42, -38, -27, -5, -6, -55, 2, -61, -33, -26, 50, 17, 51, -13, 42, 23, -8, -8, 20, 14, 26, -71, -53, -44, -23, -4, 41, 16, -7, 45, -21, -8, -10, -8, 44, -15, -22, -19, -10, -49, -26, 31, 6, 3, 37, 57, 17, 35, 35, -8, 4, -30, -15, -72, -43, 10, 16, 30, 33, -1, 5, 49, 31, -28, -22, -51, -4, 29, -4, -57, -12, -41, 13, 38, 35, 11, 36, 1, -18, -31, -11, 2, -25, -6, -17, 2, -33, 29, -33, 43, 1, 
  -1, 8, 33, -16, -42, -36, -45, -23, 10, 2, 14, -52, -43, 7, 4, 24, -1, -4, -9, 31, 37, 16, 22, -42, -49, 15, 14, 12, -3, 9, 2, 1, -23, -9, 8, 25, 7, 13, 29, 27, -13, -41, -35, 19, 18, 1, 15, -23, -22, -34, -7, -7, 12, -54, -42, 5, -5, 18, -17, -13, 2, -38, -23, -27, 21, 24, -1, 7, -18, -10, -15, 20, -46, -42, -43, -9, 14, 35, -18, -15, -22, -10, 33, -49, -31, -37, -36, -4, -5, 34, -12, -7, 14, 17, -5, 14, -13, -17, 7, 24, -35, 28, -17, -20, 35, -27, -58, -13, -43, -26, 3, 24, -22, -8, 29, -60, 5, 19, 23, 3, 0, -53, -7, -60, -57, -21, -28, -38, 30, 18, 4, -19, 4, -32, -15, -34, -14, -26, -35, 3, 37, 8, -10, 21, -4, -1, 35, 33, 44, 5, 46, -55, -32, 12, 10, -34, -51, -7, -10, 16, 30, 28, 46, -7, -21, 5, -10, -10, -1, -34, -34, 4, -28, -21, -24, 55, 7, -45, -5, -2, -57, -11, 26, 17, -17, -11, 16, 32, 0, 0, 34, -13, 43, 8, 15, 2, 25, 33, 25, 14, 0, 38, 3, 6, 10, -19, -45, -33, -26, -4, 43, -16, -14, 54, 29, -33, 14, -27, 27, 19, 23, 1, 0, 0, 0, 8, 32, 1, -79, 29, -6, -31, 44, -9, 49, 77, -6, 3, -48, 2, 14, 51, -26, 0, -2, 12, -8, -28, 32, 24, 18, 37, 1, -55, -52, 42, -19, 42, 37, 9, 1, 27, -17, -13, -25, 6, -24, 18, -34, -58, -23, 5, -10, 14, 27, -9, -19, 24, -6, -18, -27, -19, 29, -10, -5, -43, 6, 48, -23, 12, -17, -9, -51, -6, 25, 7, 18, -18, 38, -12, -9, 33, -52, -1, 18, -21, -5, 18, -47, 55, 23, 21, 36, -18, -1, 3, -9, 12, 11, 9, 8, 18, 18, -13, -26, -1, 8, 11, 7, 19, -27, -15, 6, -34, 3, 14, 18, -9, -20, 13, 8, 9, 8, 19, -26, -29, 25, -13, 19, -7, 17, 29, -14, 9, 17, -3, -1, 32, 34, -13, -16, -23, 43, 23, 29, 29, -26, -48, 26, 39, 39, -34, -31, 11, -32, 15, 8, -3, -48, 27, -18, 42, -31, 22, -36, -12, 1, 9, -6, -45, -18, -42, -48, -6, -68, -8, -26, -35, 26, 28, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0029229610227048397, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { 514, 1415, 927, -1115, -116, -925, -140, -2929, -2000, -2262, 387, -120, -1387, -1518, -1618, 2981, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 3.9800226659281179e-05, 5.0566337449708953e-05, 5.0382070185150951e-05, 3.681946691358462e-05, 4.7216319217113778e-05, 5.0614569772733375e-05, 3.9132566598709673e-05, 4.2787065467564389e-05, 6.1055397964082658e-05, 4.612172779161483e-05, 5.1347051339689642e-05, 6.4268628193531185e-05, 5.812432209495455e-05, 4.3681062379619107e-05, 4.2374718759674579e-05, 4.9952683184528723e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 32,83,127,67,-1,-36,-12,78, 18,25,11,-23,-84,-27,109,-77, 38,82,27,9,-74,-87,64,71, 
  /* [1][0][][] */ -26,100,21,64,24,-68,-25,70, -15,20,-24,-11,107,38,68,127, 112,68,71,-83,-22,-84,17,46, 
  /* [2][0][][] */ -3,46,-9,3,27,-35,29,74, 127,30,91,37,66,-102,28,120, -48,75,91,-48,27,-21,109,19, 
  /* [3][0][][] */ 68,-114,52,-72,77,-44,-127,39, -4,-113,-37,91,-4,-112,-77,19, -123,-3,-64,-72,66,-25,81,41, 
  /* [4][0][][] */ -63,-99,-113,-30,-126,-107,5,18, -80,-61,-49,-21,-43,94,30,-41, 53,52,67,-25,-74,127,-7,7, 
  /* [5][0][][] */ -110,59,28,61,-47,-127,-72,116, -112,44,-43,-24,39,41,-122,19, -68,76,20,68,-39,2,-111,80, 
  /* [6][0][][] */ 66,1,43,93,-125,-19,-18,34, 47,-108,54,-108,-65,-4,-24,57, -81,-78,-101,127,-59,56,-108,-94, 
  /* [7][0][][] */ -42,65,-20,-123,-116,111,68,-19, 23,27,28,97,44,109,16,-14, -23,-64,-127,-15,93,68,35,-51, 
  /* [8][0][][] */ -14,-88,14,83,-19,6,17,19, -69,-74,-108,61,25,-13,-127,54, -69,-54,17,27,-24,67,-55,-28, 
  /* [9][0][][] */ 3,-117,6,103,-90,92,31,15, -25,-112,-42,-60,-23,55,-57,-50, -37,-127,-90,48,-26,47,-63,23, 
  /* [10][0][][] */ -78,-18,-56,68,1,18,25,5, -127,-97,-70,32,-92,-16,-121,32, -112,-55,-88,99,-123,92,-96,91, 
  /* [11][0][][] */ -127,39,-76,83,36,22,-58,-23, -66,-70,-17,15,31,-62,-38,33, -31,-14,-62,58,-82,-81,-70,-5, 
  /* [12][0][][] */ -111,-5,-87,100,-39,41,31,-76, 9,-50,-127,-13,-116,93,-120,-78, -3,-5,17,43,-2,-45,-100,-3, 
  /* [13][0][][] */ -15,-65,-47,-81,-118,59,-70,-77, 55,15,-89,3,-127,-121,-86,-104, -63,-5,78,-21,66,-108,-89,50, 
  /* [14][0][][] */ 44,-18,85,-42,-47,57,28,-110, -59,52,80,24,-24,-19,59,-117, 91,-127,-12,121,-7,-75,-5,-121, 
  /* [15][0][][] */ 80,104,27,-7,31,-27,-10,97, 47,59,78,6,46,-34,63,88, -20,-11,127,-31,-51,-8,74,112, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0021587377414107323, 0.0027426844462752342, 0.0027326899580657482, 0.0019970634020864964, 0.0025609817821532488, 0.0027453005313873291, 0.0021225244272500277, 0.0023207420017570257, 0.0033116040285676718, 0.0025016118306666613, 0.0027850298210978508, 0.0034858875442296267, 0.0031526244711130857, 0.0023692317772656679, 0.0022983765229582787, 0.0027094003744423389, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 7375, 7265, 10771, -33494, -391, -13196, 12508, 3051, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.0614005077513866e-05, 1.2472445632738527e-05, 1.1607446140260436e-05, 7.3355854510737117e-06, 8.4320599853526801e-06, 1.1243027074669953e-05, 1.0354619917052332e-05, 1.2219970813021064e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*41] = { 
  /* [0][0][][] */ -48,40,-6,-17,-27,-21,29,-55,-41,-23,-1,-92,53,-76,-70,22,-42,-45,-48,-92,18,1,30,80,29,-8,-17,-119,12,-76,-65,34,29,-42,11,-56,10,-18,50,68,15, 38,-79,45,0,-47,46,73,-41,-4,31,59,-53,57,55,33,69,14,-39,60,-100,29,-28,-46,-16,-73,37,-10,11,-59,-20,29,-64,-53,14,0,46,7,-35,13,50,-40, 56,-53,54,-64,-69,-37,-19,42,-36,-127,-15,-28,-71,-1,-76,-27,52,-43,5,-34,-17,-10,14,-105,-83,-36,-44,-57,-50,-55,-48,-54,-33,-25,-13,30,27,50,-53,-49,1, 
  /* [1][0][][] */ -84,-67,-18,34,-127,67,-51,54,15,6,-21,-4,19,-75,24,13,-64,-16,44,69,7,-44,54,7,12,-49,-66,-36,-42,23,2,-31,-6,11,15,23,-42,-26,18,-36,52, -46,-60,4,-34,62,47,51,17,-8,-41,-31,42,-65,-99,21,3,-50,-52,-18,31,72,-8,10,-40,17,14,-23,-14,46,-13,0,-21,63,11,-26,-26,-22,12,-41,40,-61, -17,-72,-115,24,65,-13,-66,29,-45,35,51,-35,-38,-32,-58,59,80,-36,-32,22,-48,7,59,83,1,73,-13,-40,46,-25,22,-51,-26,65,49,14,-8,43,22,74,-36, 
  /* [2][0][][] */ 40,64,-86,-31,-58,-78,48,25,-22,-12,15,-54,0,-127,-71,40,48,-51,35,7,74,5,-8,53,9,-72,-68,-109,10,-39,-10,24,-52,67,90,-44,25,-16,8,-20,43, -33,6,-28,-38,-20,6,-22,37,-22,40,-104,-34,-13,44,31,-47,-42,58,41,19,52,-15,18,28,74,-17,-20,-91,-79,-22,30,-42,43,-37,-46,-78,38,-73,-11,29,-58, -52,-33,19,11,28,49,20,-64,-62,-48,-2,34,-53,-12,-121,-84,71,-60,36,69,-112,-4,52,-58,37,-80,-8,37,7,-42,-8,-59,37,-33,18,78,-37,-47,57,45,-43, 
  /* [3][0][][] */ -43,13,33,-28,104,-16,91,65,81,-67,10,-48,45,76,69,3,84,70,63,55,61,95,81,98,36,98,106,-16,120,44,24,87,17,47,47,82,-9,-11,-101,109,-36, 31,67,30,121,57,117,-33,117,109,-24,-13,26,-8,102,-6,117,76,34,86,90,79,12,92,10,-56,69,-48,73,-3,118,106,27,9,-34,14,2,-62,67,-16,92,60, 127,-34,68,78,53,77,-29,47,100,-39,-33,27,-50,25,37,30,-1,105,-44,16,-77,-18,-59,-50,57,26,74,-16,85,-34,34,-1,-55,7,-39,-79,-77,-73,18,-78,-7, 
  /* [4][0][][] */ 103,-70,-32,65,-52,8,-1,101,34,-23,-109,15,19,37,-6,95,-70,-46,-31,-54,-98,-26,-56,4,-68,-54,-4,46,42,-19,-45,5,-85,-55,-3,-106,-41,63,-47,31,43, -2,81,-17,-38,-18,68,-75,-9,-40,-29,33,-25,19,-72,-61,-50,17,13,-36,-59,33,38,34,-76,78,25,-74,-34,28,-93,56,-51,-127,18,29,-23,30,-104,14,83,-102, -92,-29,-59,2,58,12,-44,-46,-33,59,77,75,-79,32,-72,-36,6,-12,17,-3,17,-80,-28,-99,-86,-20,-49,52,8,-126,42,27,-122,39,99,67,-51,-53,-29,-12,-98, 
  /* [5][0][][] */ 27,49,7,62,23,16,-17,31,31,61,8,61,40,90,35,6,-27,17,22,37,-30,-1,40,-127,-47,-72,-6,40,-33,43,-66,43,6,-36,29,-13,-26,-47,21,-29,-63, 6,73,53,62,13,-15,-26,-33,0,-15,-21,7,66,51,36,-25,-33,42,42,37,-52,28,9,-84,-19,-36,33,38,7,-26,8,-53,24,-49,-13,2,45,-43,-76,41,-85, 89,22,39,48,23,18,47,77,62,60,19,62,30,112,97,-29,-19,-25,63,50,-18,8,-42,-59,4,29,26,16,37,58,-17,-62,-62,-44,-3,-48,23,45,-2,38,-6, 
  /* [6][0][][] */ 61,11,-40,46,-41,-79,-35,-56,-44,-108,-38,-8,-49,-71,-25,6,-38,81,4,-23,-87,23,-31,30,-19,-71,75,15,29,11,22,-57,25,-63,-45,14,-71,45,-21,-22,-38, -60,58,-23,-44,45,23,27,34,49,-52,68,-58,27,56,-43,-47,-103,38,34,-23,-124,-28,-31,-68,78,-26,25,-42,-80,52,56,-41,67,-61,79,90,75,-49,-18,-8,-45, -44,-45,-84,-27,-27,5,90,50,-97,-55,-36,-18,-81,-85,55,-108,17,-30,-22,-90,36,-33,-4,15,-127,-43,-33,-1,-61,12,11,39,-20,53,-9,-38,-72,0,11,-81,-22, 
  /* [7][0][][] */ 6,-6,23,3,47,-4,-42,61,-13,-33,53,-20,60,-86,-32,21,17,65,-2,2,-4,41,-4,51,66,19,2,50,59,50,-4,-28,59,50,10,-22,36,-10,54,-13,-11, -55,-53,-41,-101,-65,16,34,0,-1,41,-56,51,-52,-127,-48,-35,5,9,-31,5,0,37,48,53,37,-26,27,8,-38,-94,-34,19,34,42,6,2,8,15,11,19,-21, -52,-93,-52,-61,-33,3,-40,45,-21,-54,-79,-2,-20,-40,-27,50,45,-2,-10,31,30,37,-29,89,51,61,2,26,11,31,-55,-28,-59,9,-66,-52,18,4,-15,-49,19, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,41 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0027278829365968704, 0.003205516841262579, 0.0029832050204277039, 0.0018853031797334552, 0.002167105907574296, 0.0028895465657114983, 0.0026612188667058945, 0.0031406288035213947, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,98,41 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,98,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.018436804413795471, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,98,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,49,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,49,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,49,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.012059402652084827, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,49,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.10700406134128571, } };
const TfArray<1, int> quant21_zero = { 1, { 54 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension0, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 984, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension13, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension15, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension17, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_854719_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_854719_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_854719_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_854719_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_854719_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
